### ISSUE TITLE
Readme Broken Link: RFI

### ISSUE THREAD

**Issue by jimfingal** [CDTProcurement/adpq#1]
The link in the main Readme, "Digital Services - Agile Development Vender Pool Refresh Request for Interest (RFI)" 404s / goes to a broken page: https://github.com/CDTProcurement/adpq/blob/master/Pre-Release%20RFI%20CDT-ADPQ-0117%20-%20ADPQ%20Vendor%20Pool%20Refresh.pdf

**Comment by TiffanyAngulo** [comment]
Thank you. This link appears to be to the Pre-Release draft. The final draft has been published.
